### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Lord-Bach**

### CODE REVIEW

**Review by dkkapur — APPROVED** [review]
LGTM, thanks for adding this.

**Comment by dkkapur** [comment]
Wait @simonkim0515 - just reread. You have this below:
Screen Shot 2023-03-28 at 6 07 42 PM

**Comment by dkkapur** [comment]
Actually FWIW, I agree with the change. Makes sense in terms of readability and ease of friction ✅ in case folks miss the rest of it.

**Comment by data-programs** [comment]
KYC

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Pull request merged**
