### PR TITLE
Create datacap-application-proposal.yaml

### PR DESCRIPTION
**Pull request by dkkapur**
Introducing a yaml based issue template form - should result in improved UX, higher quality data collection from clients.

### CODE REVIEW

**Comment by ribasushi** [comment]
@dkkapur you have the `body` key twice in a map ( **not** an array ). I do not think this is valid YAML...

**Comment by fengqiangjun** [comment]
We are contacting sp and will start packaging shortly.

**Comment by dkkapur** [comment]
@fengqiangjun where was this comment supposed to be?

**Comment by dkkapur** [comment]
Not relevant anymore. Have a better form/format!

**Pull request closed without merging**
